#!/bin/sh
#place this in /etc/init.d
#and make it executable
#thanks fly to https://haus-automatisierung.com/hardware/fhem/2016/07/14/fhem-tutorial-reihe-part-11-benachrichtigung-mit-bild-bei-bewegung.html
### BEGIN INIT INFO
# Provides: camerawatch
# Required-Start: $network $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start daemon at boot time for camerawatch
# Description: Enable service provided by daemon.
### END INIT INFO
export PATH=$PATH:/usr/local/bin
PID=`cat /opt/fhem/camerawatch.sh.pid 2>/dev/null`
#echo $PID
case "$1" in
start)
if ps -p $PID > /dev/null 2>&1; then
    echo "Camerawatch is already running"
else
    su - "root" -c "bash /opt/fhem/camerawatch.sh > /dev/null 2>&1 &"
    #debug: launch with output
    #su - "root" -c "bash /opt/fhem/camerawatch.sh &"echo "Camerawatch starting"
    sleep 2
    $0 status
fi
;;
stop)
if ! ps -p $PID > /dev/null 2>&1; then
    echo "Camerawatch is not running"
else
    kill $PID
    echo "Camerawatch closed"
fi
;;
restart)
if ! ps -p $PID > /dev/null 2>&1; then
    $0 start
else
    $0 stop
    $0 start
fi
;;
status)
if ps -p $PID > /dev/null 2>&1; then
    echo "Camerawatch is running PID $PID"
else
    echo "Camerawatch is not running"
fi
;;
*)
echo "Usage: $0 {start|stop|status|restart}"
exit 1
;;
esac
exit 0
